### ISSUE TITLE
Please add instructions for building on Linux

### ISSUE THREAD

**Issue by FriederHannenheim** [ambrosiogabe/MathAnimation#39]

**Comment by ambrosiogabe** [comment]
This is only supported on Windows right, now. I've updated the readme with this information.

**Comment by ThatOneCalculator** [comment]
If it is only on Windows, then why would you include Linux package manager instructions in the readme? 

![Screenshot_20230102-103630](https://user-images.githubusercontent.com/44733677/210268390-7f3e9165-493d-4dc0-917b-da692dff255e.png)

**Comment by ambrosiogabe** [comment]
@ThatOneCalculator Yes, this is using `pacman` through `msys2` since it's the only way to compile ffmpeg on Windows. It's like Wine on Linux, except it's the Wine for running linux on Windows. 

It's part of the build instructions for ffmpeg for native compilation on Windows. Some helpful folks are working on adding Linux support, so I'll be adding some additional information in the next week or so :)
